spring.application.name=Student-Management-System

# Disable Docker Compose integration (we manage it manually)
spring.docker.compose.enabled=false

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/studentmanagementsystem
spring.datasource.username=postgres
spring.datasource.password=3106
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# Server Configuration
server.error.include-message=always
server.error.include-binding-errors=always
